version: '3.8'

services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared
    container_name: cloudflared
    hostname: cloudflared
    restart: unless-stopped
    network_mode: "host"
    command: tunnel run
    environment:
      - "TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}"